package ine5605g6.detran.iu.menu;

public enum Opcao {
	MEMORIA,
	ARQUIVO,
	MOSTRAR_QTD,
	SAIR,
	C_CONDUTOR_MANUAL,
	C_CONDUTOR_AUTO,
	C_VEICULO_MANUAL,
	C_VEICULO_AUTO,
	C_INFRACAO_MANUAL,
	C_INFRACAO_AUTO,
	PESQUISAR_CONDUTOR,
	PESQUISAR_VEICULO,
	PESQUISAR_PERIODO,
	PESQUISAR_MAIORES
}
